id: I7CCC4BA6
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:19:50.773880+00:00
last_modified: 2022-12-14 18:19:50.773887+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-062-011
  eft-text-version: 1.1.3 2020
  title: Toh_211-Teaching_the_Fundamental_Exposition_of_Dependent_Arising-v2
bases:
  C4D0:
    source_metadata: null
    order: 1
    base_file: C4D0.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
